version: "3.9"

services:
  db:
    image: postgres:15
    container_name: hosting_sifrovacek_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sifrovacky_user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hosting_sifrovacek
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    container_name: hosting_sifrovacek_backend
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: .
    container_name: hosting_sifrovacek_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data: